### ISSUE TITLE
Memory watch

### ISSUE THREAD

**Issue by Sekanor** [Sekanor/SM63PracticeHack#10]
- Provide a tool to see the content of variables directly on screen.

**Comment by KevinKib** [comment]
For this command two things would be really nice :
- Figuring out how to break the limit of 6 lines of text
- Giving nice names to the variables so someone can watch Mario's horizontal speed without knowing it is stored in `_root.Course.Char.x` or something like that. Documenting those names as well; while still allowing the variables to work

I'll take a look on the first one :)
